let data = [
    {
        id: 1,
        category: {id: 1, name: 'Кошки'},
        brand: {id: 1, name: 'Американская'},
        name: 'Джипси',
        price: 2500,
        photo: 'cat1.jpg',
    },
    {
        id: 2,
        category: {id: 1, name: 'Кошки'},
        brand: {id: 1, name: 'Американская'},
        name: 'Ушко',
        price: 5000,
        photo: 'cat2.jpg',
    },
    {
        id: 3,
        category: {id: 1, name: 'Кошки'},
        brand: {id: 2, name: 'Балинезийская'},
        name: 'Хвостушка',
        price: 3500,
        photo: 'cat3.jpg',
    },
    {
        id: 4,
        category: {id: 1, name: 'Кошки'},
        brand: {id: 3, name: 'Сингапурская'},
        name: 'Зубастик',
        price: 1800,
        photo: 'cat4.jpg',
    },
    {
        id: 5,
        category: {id: 1, name: 'Кошки'},
        brand: {id: 4, name: 'Бирманская'},
        name: 'Джипси',
        price: 2500,
        photo: 'cat5.jpg',
    },
    {
        id: 6,
        category: {id: 1, name: 'Кошки'},
        brand: {id: 4, name: 'Бирманская'},
        name: 'Ушко',
        price: 5000,
        photo: 'cat6.jpg',
    },
    {
        id: 7,
        category: {id: 1, name: 'Кошки'},
        brand: {id: 5, name: 'Корниш-рекс'},
        name: 'Хвостушка',
        price: 3500,
        photo: 'cat7.jpg',
    },
    {
        id: 8,
        category: {id: 1, name: 'Кошки'},
        brand: {id: 6, name: 'Сноу-шу'},
        name: 'Зубастик',
        price: 1800,
        photo: 'cat8.jpg',
    },


    {
        id: 9,
        category: {id: 2, name: 'Волки'},
        brand: {id: 7, name: 'Гривистый'},
        name: 'Барни',
        price: 15000,
        photo: 'wolf1.jpg',
    },
    {
        id: 10,
        category: {id: 2, name: 'Волки'},
        brand: {id: 7, name: 'Гривистый'},
        name: 'Шелдон',
        price: 25000,
        photo: 'wolf2.jpg',
    },
    {
        id: 11,
        category: {id: 2, name: 'Волки'},
        brand: {id: 8, name: 'Мелвильский'},
        name: 'Тимон',
        price: 17600,
        photo: 'wolf3.jpg',
    },
    {
        id: 12,
        category: {id: 2, name: 'Волки'},
        brand: {id: 8, name: 'Мелвильский'},
        name: 'Соник',
        price: 13000,
        photo: 'wolf4.jpg',
    },
    {
        id: 13,
        category: {id: 2, name: 'Волки'},
        brand: {id: 9, name: 'Лирый'},
        name: 'Майк',
        price: 8000,
        photo: 'wolf5.jpg',
    },
];

export default data;